# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: azul/zulu-openjdk:17-latest

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - test
  - build-publish
  - downstream

default:
  tags: [$RUNNER_TAGS]

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y liblapack3
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"

buildLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build-publish
  script:
    - ./gradlew clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  rules:
    - if: $ARTIFACTORY_USERNAME && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "stable")
      changes:
        # exclude README only changes from pipeline
        - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
        - "**/src/main/java/**/*"

trigger_sirius_frontend:
  stage: downstream
  trigger:
    project: "$SIRIUS_FRONTEND_PROJECT"
    strategy: depend
    branch: $CI_COMMIT_REF_NAME
  rules:
    - if: $ARTIFACTORY_USERNAME && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "stable")
  allow_failure: true