# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
default:
  image: azul/zulu-openjdk:21-latest
  tags: [$RUNNER_TAGS]

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - test-libs
  - build-publish-libs
  - build-app
  - test-app
  - publish-app

before_script:
  - rm /etc/apt/sources.list.d/zulu-openjdk.list
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg unzip liblapack-dev curl git -y )'
  - VSNAP=$(head -2 sirius_cli/src/main/resources/sirius_frontend.build.properties | tail -1 | cut -d '=' -f 2)

test:
  stage: test-libs
  script:
    - apt-get update
    - apt-get install -y liblapack3
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"

buildLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build-publish-libs
  script:
    - ./gradlew clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  rules:
    - if: $ARTIFACTORY_USERNAME && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "stable")
      changes:
        # exclude README only changes from pipeline
        - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
        - "**/src/main/java/**/*"

buildCLI:
  stage: build-app
  script:
    - ./gradlew :sirius_dist:sirius_cli_single_os:publishSiriusMSPublicationToMavenLocal -P "build.sirius.starter.jdk.include=true"
    - mkdir maven_artifacts
    - mv ~/.m2/repository/de/unijena/bioinf/ms/siriusMS/$VSNAP maven_artifacts
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./maven_artifacts/$VSNAP
    expire_in: 3 days
  only:
    refs:
      - master
      - stable

buildGUI:
  stage: build-app
  script:
    - ./gradlew :sirius_dist:sirius_gui_dist:publishSiriusMSPublicationToMavenLocal -P "build.sirius.native.openjfx.exclude=true" -P "build.sirius.starter.jdk.include=true"
    - mkdir maven_artifacts
    - mv ~/.m2/repository/de/unijena/bioinf/ms/siriusMS/$VSNAP maven_artifacts
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./maven_artifacts/$VSNAP
    expire_in: 3 days
  only:
    refs:
      - master
      - stable

testCLI:
  stage: test-app
  script:
    - mkdir unzipped
    - unzip maven_artifacts/$VSNAP/siriusMS-$VSNAP-linux64-headless.zip -d unzipped
    - ./unzipped/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
    - ./gradlew :sirius_dist:sirius_cli_single_os:distImageTestCICD
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildCLI]
  dependencies:
    - buildCLI
  only:
    refs:
      - master
      - stable

testGUI:
  stage: test-app
  script:
    - mkdir unzipped
    - unzip maven_artifacts/$VSNAP/siriusMS-$VSNAP-linux64.zip -d unzipped
    - ./unzipped/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
    - ./gradlew :sirius_dist:sirius_cli_single_os:distImageTestCICD
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildGUI]
  dependencies:
    - buildGUI
  only:
    refs:
      - master
      - stable

publishCLI:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: publish-app
  script:
    - cd maven_artifacts/$VSNAP
    - curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN -X PUT "https://bio.informatik.uni-jena.de/repository/dist-snapshot-local/de/unijena/bioinf/ms/siriusMS/$VSNAP/siriusMS-$VSNAP-linux64-headless.zip" -T siriusMS-$VSNAP-linux64-headless.zip
    - curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN -X PUT "https://bio.informatik.uni-jena.de/repository/dist-snapshot-local/de/unijena/bioinf/ms/siriusMS/$VSNAP/siriusMS-$VSNAP.pom" -T siriusMS-$VSNAP.pom
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildCLI, testCLI]
  dependencies:
    - buildCLI
  only:
    refs:
      - master
      - stable

publishGUI:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: publish-app
  script:
    - cd maven_artifacts/$VSNAP
    - curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN -X PUT "https://bio.informatik.uni-jena.de/repository/dist-snapshot-local/de/unijena/bioinf/ms/siriusMS/$VSNAP/siriusMS-$VSNAP-linux64.zip" -T siriusMS-$VSNAP-linux64.zip
    - curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN -X PUT "https://bio.informatik.uni-jena.de/repository/dist-snapshot-local/de/unijena/bioinf/ms/siriusMS/$VSNAP/siriusMS-$VSNAP.pom" -T siriusMS-$VSNAP.pom
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildGUI, testGUI]
  dependencies:
    - buildGUI
  only:
    refs:
      - master
      - stable

#push to github to build for multiple OSs
pushToGitHub:
  stage: publish-app
  script:
    - git config --global user.email "${GITLAB_GITHUB_SIRIUS_USERNAME}"
    - git config --global user.name "boeckergitlab"
    - git remote show origin
    - git remote set-url --push origin git@github.com:sirius-ms/sirius.git
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [testCLI, testGUI]
  only:
    refs:
      - stable
      - master